In [2]:
import torch
import numpy as np
from luwiji.neural_network import illustration, demo

## Sample data

In [3]:
a = demo.example_data_1
a

array([[[ 52,  72, 154, 174,  87],
        [120, 238, 164, 188,   2],
        [ 58,  68, 135, 201, 200],
        [152,  64,  40, 172,  18],
        [ 64, 187, 141,  60, 195]],

       [[114,  32, 113, 199, 219],
        [107, 170,  67,  80, 105],
        [244,  15,  37, 163, 213],
        [118, 130, 225, 156,  61],
        [108, 177, 127, 135,  12]],

       [[193,  51, 220, 150, 232],
        [  1, 178, 174, 228, 237],
        [ 44,  16, 219,  12, 142],
        [188,  61,  34, 190, 189],
        [221,   5, 245,   2,  91]]])

## Tensor

#### Numpy (array), Pandas (Dataframe), Pytorch(Tensor)

In [4]:
# convert dari numpy array ke tensor pytorch agar dapat diolah
torch.Tensor(a)

tensor([[[ 52.,  72., 154., 174.,  87.],
         [120., 238., 164., 188.,   2.],
         [ 58.,  68., 135., 201., 200.],
         [152.,  64.,  40., 172.,  18.],
         [ 64., 187., 141.,  60., 195.]],

        [[114.,  32., 113., 199., 219.],
         [107., 170.,  67.,  80., 105.],
         [244.,  15.,  37., 163., 213.],
         [118., 130., 225., 156.,  61.],
         [108., 177., 127., 135.,  12.]],

        [[193.,  51., 220., 150., 232.],
         [  1., 178., 174., 228., 237.],
         [ 44.,  16., 219.,  12., 142.],
         [188.,  61.,  34., 190., 189.],
         [221.,   5., 245.,   2.,  91.]]])

In [6]:
torch.FloatTensor(a)

tensor([[[ 52.,  72., 154., 174.,  87.],
         [120., 238., 164., 188.,   2.],
         [ 58.,  68., 135., 201., 200.],
         [152.,  64.,  40., 172.,  18.],
         [ 64., 187., 141.,  60., 195.]],

        [[114.,  32., 113., 199., 219.],
         [107., 170.,  67.,  80., 105.],
         [244.,  15.,  37., 163., 213.],
         [118., 130., 225., 156.,  61.],
         [108., 177., 127., 135.,  12.]],

        [[193.,  51., 220., 150., 232.],
         [  1., 178., 174., 228., 237.],
         [ 44.,  16., 219.,  12., 142.],
         [188.,  61.,  34., 190., 189.],
         [221.,   5., 245.,   2.,  91.]]])

In [10]:
a = torch.LongTensor(a)
a

tensor([[[ 52,  72, 154, 174,  87],
         [120, 238, 164, 188,   2],
         [ 58,  68, 135, 201, 200],
         [152,  64,  40, 172,  18],
         [ 64, 187, 141,  60, 195]],

        [[114,  32, 113, 199, 219],
         [107, 170,  67,  80, 105],
         [244,  15,  37, 163, 213],
         [118, 130, 225, 156,  61],
         [108, 177, 127, 135,  12]],

        [[193,  51, 220, 150, 232],
         [  1, 178, 174, 228, 237],
         [ 44,  16, 219,  12, 142],
         [188,  61,  34, 190, 189],
         [221,   5, 245,   2,  91]]])

## Shape

In [11]:
a.shape
# 3,5,5 adalah channel, height, width. harus dirubah ke nchw(data,channel,height,width) agar dapat diterima pytorch

torch.Size([3, 5, 5])

## Reshape

In [14]:
a.reshape(3, 25)

tensor([[ 52,  72, 154, 174,  87, 120, 238, 164, 188,   2,  58,  68, 135, 201,
         200, 152,  64,  40, 172,  18,  64, 187, 141,  60, 195],
        [114,  32, 113, 199, 219, 107, 170,  67,  80, 105, 244,  15,  37, 163,
         213, 118, 130, 225, 156,  61, 108, 177, 127, 135,  12],
        [193,  51, 220, 150, 232,   1, 178, 174, 228, 237,  44,  16, 219,  12,
         142, 188,  61,  34, 190, 189, 221,   5, 245,   2,  91]])

In [15]:
a.view(3, 25)

tensor([[ 52,  72, 154, 174,  87, 120, 238, 164, 188,   2,  58,  68, 135, 201,
         200, 152,  64,  40, 172,  18,  64, 187, 141,  60, 195],
        [114,  32, 113, 199, 219, 107, 170,  67,  80, 105, 244,  15,  37, 163,
         213, 118, 130, 225, 156,  61, 108, 177, 127, 135,  12],
        [193,  51, 220, 150, 232,   1, 178, 174, 228, 237,  44,  16, 219,  12,
         142, 188,  61,  34, 190, 189, 221,   5, 245,   2,  91]])

In [17]:
# NCHW (4 dimensi) sesuai dengan format pytorch
a = a.view(1, 3, 5,5)
a

tensor([[[[ 52,  72, 154, 174,  87],
          [120, 238, 164, 188,   2],
          [ 58,  68, 135, 201, 200],
          [152,  64,  40, 172,  18],
          [ 64, 187, 141,  60, 195]],

         [[114,  32, 113, 199, 219],
          [107, 170,  67,  80, 105],
          [244,  15,  37, 163, 213],
          [118, 130, 225, 156,  61],
          [108, 177, 127, 135,  12]],

         [[193,  51, 220, 150, 232],
          [  1, 178, 174, 228, 237],
          [ 44,  16, 219,  12, 142],
          [188,  61,  34, 190, 189],
          [221,   5, 245,   2,  91]]]])

In [18]:
a.shape

torch.Size([1, 3, 5, 5])

## convert dari torch tensor ke numpy array

In [19]:
a.numpy()

array([[[[ 52,  72, 154, 174,  87],
         [120, 238, 164, 188,   2],
         [ 58,  68, 135, 201, 200],
         [152,  64,  40, 172,  18],
         [ 64, 187, 141,  60, 195]],

        [[114,  32, 113, 199, 219],
         [107, 170,  67,  80, 105],
         [244,  15,  37, 163, 213],
         [118, 130, 225, 156,  61],
         [108, 177, 127, 135,  12]],

        [[193,  51, 220, 150, 232],
         [  1, 178, 174, 228, 237],
         [ 44,  16, 219,  12, 142],
         [188,  61,  34, 190, 189],
         [221,   5, 245,   2,  91]]]], dtype=int64)

In [23]:
# convert to python
a.tolist()

[[[[52, 72, 154, 174, 87],
   [120, 238, 164, 188, 2],
   [58, 68, 135, 201, 200],
   [152, 64, 40, 172, 18],
   [64, 187, 141, 60, 195]],
  [[114, 32, 113, 199, 219],
   [107, 170, 67, 80, 105],
   [244, 15, 37, 163, 213],
   [118, 130, 225, 156, 61],
   [108, 177, 127, 135, 12]],
  [[193, 51, 220, 150, 232],
   [1, 178, 174, 228, 237],
   [44, 16, 219, 12, 142],
   [188, 61, 34, 190, 189],
   [221, 5, 245, 2, 91]]]]

In [25]:
a = demo.example_data_2
a

tensor(5)

In [26]:
a.item()

5